INSERT INTO HISTORIALABORAL (id,mesesaportados, regularidad) values (1,30,'REGULAR');
insert into DICTAMEN (id,DICTAMENPRIMERAINSTANCIA,DICTAMENSEGUNDAINSTANCIA,DICTAMENTERCERAINSTANCIA,PORCENTAJEINVALIDEZ) values (1,'FAVORABLE','','',66);
insert into PERSONA (cuil,APELLIDONOMBRE,EDAD,FECHANACIMIENTO,SEXO,DICTAMEN_ID,HISTORIA_ID) values (111,'LEENEN, Leonardo Gabriel',32,'1977-06-27','M',1,1);

INSERT INTO HISTORIALABORAL (id,mesesaportados, regularidad) values (2,30,'IRREGULAR');
insert into DICTAMEN (id,DICTAMENPRIMERAINSTANCIA,DICTAMENSEGUNDAINSTANCIA,DICTAMENTERCERAINSTANCIA,PORCENTAJEINVALIDEZ) values (2,'NO FAVORABLE','','',80);
insert into PERSONA (cuil,APELLIDONOMBRE,EDAD,FECHANACIMIENTO,SEXO,DICTAMEN_ID,HISTORIA_ID) values (222,'BARROS REQUEIJO, Fabian Daniel',48,'1963-06-27','M',2,2);

INSERT INTO HISTORIALABORAL (id,mesesaportados, regularidad) values (3,120,'REGULAR');
insert into DICTAMEN (id,DICTAMENPRIMERAINSTANCIA,DICTAMENSEGUNDAINSTANCIA,DICTAMENTERCERAINSTANCIA,PORCENTAJEINVALIDEZ) values (3,'NO FAVORABLE','FAVORABLE','',65);
insert into PERSONA (cuil,APELLIDONOMBRE,EDAD,FECHANACIMIENTO,SEXO,DICTAMEN_ID,HISTORIA_ID) values (333,'RODRIGUEZ, Juan Pablo',65,'1945-06-27','M',3,3);

INSERT INTO HISTORIALABORAL (id,mesesaportados, regularidad) values (4,24,'IRREGULAR');
insert into DICTAMEN (id,DICTAMENPRIMERAINSTANCIA,DICTAMENSEGUNDAINSTANCIA,DICTAMENTERCERAINSTANCIA,PORCENTAJEINVALIDEZ) values (4,'FAVORABLE','','',89);
insert into PERSONA (cuil,APELLIDONOMBRE,EDAD,FECHANACIMIENTO,SEXO,DICTAMEN_ID,HISTORIA_ID) values (444,'Gonzalez,Antonio',70,'1945-06-27','M',4,4);