
package ar.gob.anses.prissa.mi.asistente_reglas.seam.action.cq.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-05/25/2009 08:11 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AsistenteDeReglasSoap", targetNamespace = "http://bfdev64:8095/servicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AsistenteDeReglasSoap {


    /**
     * Se conecta a ClearQuest y crea un registro
     * 
     * @param datosDeArchivo
     * @param textoXML
     * @param nombreDeArchivo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://bfdev64:8095/servicios/crearRegistroEnClearQuest")
    @WebResult(name = "crearRegistroEnClearQuestResult", targetNamespace = "http://bfdev64:8095/servicios/")
    @RequestWrapper(localName = "crearRegistroEnClearQuest", targetNamespace = "http://bfdev64:8095/servicios/", className = "ar.gob.anses.prissa.mi.asistente_reglas.seam.action.cq.ws.CrearRegistroEnClearQuest")
    @ResponseWrapper(localName = "crearRegistroEnClearQuestResponse", targetNamespace = "http://bfdev64:8095/servicios/", className = "ar.gob.anses.prissa.mi.asistente_reglas.seam.action.cq.ws.CrearRegistroEnClearQuestResponse")
    public String crearRegistroEnClearQuest(
        @WebParam(name = "textoXML", targetNamespace = "http://bfdev64:8095/servicios/")
        String textoXML,
        @WebParam(name = "nombreDeArchivo", targetNamespace = "http://bfdev64:8095/servicios/")
        String nombreDeArchivo,
        @WebParam(name = "datosDeArchivo", targetNamespace = "http://bfdev64:8095/servicios/")
        byte[] datosDeArchivo);

}
