
package ar.gob.anses.prissa.mi.asistente_reglas.seam.action.cq.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import ar.gob.anses.prissa.mi.asistente_reglas.seam.action.cq.PropertiesHelper;

/**
 * Acceso a la base de datos de ClearQuest desde un servicio Web
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-05/25/2009 08:11 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AsistenteDeReglas", targetNamespace = "http://bfdev64:8095/servicios/", wsdlLocation = "http://gsytsissgp01/CQ/AsistenteDeReglas.asmx?wsdl")
public class AsistenteDeReglas
    extends Service
{

    private final static URL ASISTENTEDEREGLAS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            //url = new URL("http://gsytsissgp01/CQ/AsistenteDeReglas.asmx?wsdl");
        	url = new URL(PropertiesHelper.getInstance().getProperties("cq").getProperty("ws.url"));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ASISTENTEDEREGLAS_WSDL_LOCATION = url;
    }

    public AsistenteDeReglas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsistenteDeReglas() {
        super(ASISTENTEDEREGLAS_WSDL_LOCATION, new QName("http://bfdev64:8095/servicios/", "AsistenteDeReglas"));
    }

    /**
     * 
     * @return
     *     returns AsistenteDeReglasSoap
     */
    @WebEndpoint(name = "AsistenteDeReglasSoap")
    public AsistenteDeReglasSoap getAsistenteDeReglasSoap() {
        return (AsistenteDeReglasSoap)super.getPort(new QName("http://bfdev64:8095/servicios/", "AsistenteDeReglasSoap"), AsistenteDeReglasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsistenteDeReglasSoap
     */
    @WebEndpoint(name = "AsistenteDeReglasSoap")
    public AsistenteDeReglasSoap getAsistenteDeReglasSoap(WebServiceFeature... features) {
        return (AsistenteDeReglasSoap)super.getPort(new QName("http://bfdev64:8095/servicios/", "AsistenteDeReglasSoap"), AsistenteDeReglasSoap.class, features);
    }

}
